"""initial schema

M2 저장 계층의 초기 스키마. `app/models/tables.py`에서 --autogenerate로 뽑았다.

테이블 5개: issues / issue_labels / issue_comments / issue_first_responses /
sync_state. 각 제약을 왜 걸었는지는 ORM 모델의 docstring에 있다.

`create_all()`로 만든 테스트 DB만 믿지 않는다. ORM만 고치면 테스트는 통과하고
배포 DB에서만 깨지므로, 스키마 변경은 항상 마이그레이션과 같은 커밋에 담는다
(`CLAUDE.md` 7절).

Revision ID: 0741fb4039e2
Revises:
Create Date: 2026-08-26 20:03:30.111430

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0741fb4039e2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("repo_full_name", sa.String(length=255), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "open", "closed", name="issue_state", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("state_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("author_login", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("author_type", sa.String(length=64), nullable=False),
        sa.Column("author_association", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "comments_count >= 0", name=op.f("ck_issues_comments_count_non_negative")
        ),
        sa.CheckConstraint("number > 0", name=op.f("ck_issues_number_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint(
            "repo_full_name", "number", name=op.f("uq_issues_repo_full_name_number")
        ),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issues_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "sync_state",
        sa.Column("repo_full_name", sa.String(length=255), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("since_cursor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(etag IS NULL) = (request_fingerprint IS NULL)",
            name=op.f("ck_sync_state_etag_requires_fingerprint"),
        ),
        sa.PrimaryKeyConstraint("repo_full_name", "resource", name=op.f("pk_sync_state")),
    )
    op.create_table(
        "issue_comments",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("issue_id", sa.BigInteger(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("author_login", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("author_type", sa.String(length=64), nullable=False),
        sa.Column("author_association", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_comments_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_comments")),
    )
    with op.batch_alter_table("issue_comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issue_comments_issue_id"), ["issue_id"], unique=False)

    op.create_table(
        "issue_first_responses",
        sa.Column("issue_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment_id", sa.BigInteger(), nullable=True),
        sa.Column("responder_login", sa.String(length=255), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(responded_at IS NULL AND comment_id IS NULL AND responder_login IS NULL)"
            " OR (responded_at IS NOT NULL AND comment_id IS NOT NULL"
            " AND responder_login IS NOT NULL)",
            name=op.f("ck_issue_first_responses_response_fields_all_or_none"),
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_first_responses_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", name=op.f("pk_issue_first_responses")),
    )
    op.create_table(
        "issue_labels",
        sa.Column("issue_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_issue_labels_name_not_empty")),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_labels_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", "name", name=op.f("pk_issue_labels")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issue_labels")
    op.drop_table("issue_first_responses")
    with op.batch_alter_table("issue_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issue_comments_issue_id"))

    op.drop_table("issue_comments")
    op.drop_table("sync_state")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issues_updated_at"))
        batch_op.drop_index(batch_op.f("ix_issues_created_at"))

    op.drop_table("issues")
    # ### end Alembic commands ###
